Description: >
  Cloudfront distribution for UdaPeople.

Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String


Resources:
  
  CloudFrontOriginAccessIdentity: # old CloudFrontOriginAccessIdentity
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  WebpageCDN: #switches from blue to green
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins: # changing the cloudfront from 1 s3-bucket to another s3-bucket
          - DomainName: !Sub "udapeople-${WorkflowID}.s3.amazonaws.com"
            Id: webpage
            S3OriginConfig: # new CloudFrontOriginAccessIdentity
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowID}
    Description: URL for website hosted on S3
    Export:
      Name: WorkflowID
